const fs = require('fs');

const rawData = {
  "CS": [
    ["Introduction to Algorithms", "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein", "MIT Press", "4th Edition", "2022"],
    ["Artificial Intelligence: A Modern Approach", "Stuart Russell, Peter Norvig", "Pearson", "4th Edition", "2020"],
    ["Structure and Interpretation of Computer Programs", "Harold Abelson, Gerald Jay Sussman", "MIT Press", "2nd Edition", "1996"],
    ["Computer Systems: A Programmer's Perspective", "Randal E. Bryant, David R. O'Hallaron", "Pearson", "3rd Edition", "2015"],
    ["Operating System Concepts", "Abraham Silberschatz, Peter B. Galvin, Greg Gagne", "Wiley", "10th Edition", "2018"],
    ["Computer Networks", "Andrew S. Tanenbaum, David J. Wetherall", "Pearson", "6th Edition", "2021"],
    ["Compilers: Principles, Techniques, and Tools", "Alfred V. Aho, Monica S. Lam, Ravi Sethi", "Addison-Wesley", "2nd Edition", "2006"],
    ["Database System Concepts", "Abraham Silberschatz, Henry F. Korth, S. Sudarshan", "McGraw-Hill", "7th Edition", "2019"],
    ["Algorithm Design", "Jon Kleinberg, Éva Tardos", "Pearson", "1st Edition", "2005"],
    ["Computer Organization and Design", "David A. Patterson, John L. Hennessy", "Morgan Kaufmann", "6th Edition", "2020"],
    ["Modern Operating Systems", "Andrew S. Tanenbaum, Herbert Bos", "Pearson", "5th Edition", "2022"],
    ["Python Crash Course", "Eric Matthes", "No Starch Press", "3rd Edition", "2023"],
    ["The C Programming Language", "Brian W. Kernighan, Dennis M. Ritchie", "Prentice Hall", "2nd Edition", "1988"],
    ["Digital Design and Computer Architecture", "David Harris, Sarah Harris", "Morgan Kaufmann", "2nd Edition", "2012"],
    ["Data Structures and Algorithms in Java", "Robert Lafore", "Sams Publishing", "2nd Edition", "2017"],
    ["Foundations of Computer Science", "Alfred V. Aho, Jeffrey D. Ullman", "W. H. Freeman", "1st Edition", "1994"],
    ["Introduction to the Theory of Computation", "Michael Sipser", "Cengage Learning", "3rd Edition", "2012"],
    ["Discrete Mathematics and Its Applications", "Kenneth H. Rosen", "McGraw-Hill", "8th Edition", "2018"],
    ["Programming Language Pragmatics", "Michael L. Scott", "Morgan Kaufmann", "4th Edition", "2015"],
    ["Distributed Systems: Principles and Paradigms", "Andrew S. Tanenbaum, Maarten van Steen", "Pearson", "3rd Edition", "2017"],
    ["Deep Learning", "Ian Goodfellow, Yoshua Bengio, Aaron Courville", "MIT Press", "1st Edition", "2016"],
    ["Head First Design Patterns", "Eric Freeman, Elisabeth Robson", "O'Reilly Media", "2nd Edition", "2020"],
    ["Code: The Hidden Language of Hardware and Software", "Charles Petzold", "Microsoft Press", "2nd Edition", "2022"],
    ["The Art of Computer Programming", "Donald E. Knuth", "Addison-Wesley", "3rd Edition", "2011"],
    ["Computer Graphics: Principles and Practice", "John F. Hughes, Andries van Dam", "Addison-Wesley", "3rd Edition", "2013"],
    ["Automata Theory, Languages, and Computation", "John E. Hopcroft, Rajeev Motwani, Jeffrey D. Ullman", "Pearson", "3rd Edition", "2006"],
    ["Programming Pearls", "Jon Bentley", "Addison-Wesley", "2nd Edition", "1999"],
    ["Computer Architecture: A Quantitative Approach", "John L. Hennessy, David A. Patterson", "Morgan Kaufmann", "6th Edition", "2017"],
    ["Logic in Computer Science", "Michael Huth, Mark Ryan", "Cambridge University Press", "2nd Edition", "2004"],
    ["Elements of the Theory of Computation", "Harry R. Lewis, Christos H. Papadimitriou", "Prentice Hall", "2nd Edition", "1997"],
    ["Principles of Computer System Design", "Jerome H. Saltzer, M. Frans Kaashoek", "Morgan Kaufmann", "1st Edition", "2009"],
    ["Computer Science: An Overview", "J. Glenn Brookshear, Dennis Brylow", "Pearson", "13th Edition", "2019"],
    ["Concrete Mathematics", "Ronald L. Graham, Donald E. Knuth, Oren Patashnik", "Addison-Wesley", "2nd Edition", "1994"],
    ["Data Mining: Concepts and Techniques", "Jiawei Han, Micheline Kamber, Jian Pei", "Morgan Kaufmann", "3rd Edition", "2011"],
    ["High Performance Computing", "John Levesque, Gene Wagenbreth", "CRC Press", "1st Edition", "2010"],
    ["Essentials of Programming Languages", "Daniel P. Friedman, Mitchell Wand", "MIT Press", "3rd Edition", "2008"],
    ["Artificial Intelligence: Structures and Strategies", "George F. Luger", "Pearson", "6th Edition", "2008"],
    ["Cryptography and Network Security", "William Stallings", "Pearson", "8th Edition", "2020"],
    ["Principles of Information Security", "Michael E. Whitman, Herbert J. Mattord", "Cengage Learning", "7th Edition", "2021"],
    ["Information Theory, Inference and Learning Algorithms", "David J. C. MacKay", "Cambridge University Press", "1st Edition", "2003"],
    ["Quantum Computation and Quantum Information", "Michael A. Nielsen, Isaac L. Chuang", "Cambridge University Press", "10th Anniversary Edition", "2010"],
    ["Introduction to High Performance Scientific Computing", "Victor Eijkhout", "Lulu Press", "2nd Edition", "2020"]
  ],
  "SE": [
    ["Clean Code: A Handbook of Agile Software Craftsmanship", "Robert C. Martin", "Prentice Hall", "1st Edition", "2008"],
    ["Design Patterns: Elements of Reusable Object-Oriented Software", "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides", "Addison-Wesley", "1st Edition", "1994"],
    ["Refactoring: Improving the Design of Existing Code", "Martin Fowler", "Addison-Wesley", "2nd Edition", "2018"],
    ["The Pragmatic Programmer", "Andrew Hunt, David Thomas", "Addison-Wesley", "2nd Edition", "2019"],
    ["Software Engineering", "Ian Sommerville", "Pearson", "10th Edition", "2015"],
    ["Software Engineering: A Practitioner's Approach", "Roger S. Pressman, Bruce R. Maxim", "McGraw-Hill", "9th Edition", "2019"],
    ["Code Complete: A Practical Handbook of Software Construction", "Steve McConnell", "Microsoft Press", "2nd Edition", "2004"],
    ["Working Effectively with Legacy Code", "Michael Feathers", "Prentice Hall", "1st Edition", "2004"],
    ["Continuous Delivery", "Jez Humble, David Farley", "Addison-Wesley", "1st Edition", "2010"],
    ["Building Microservices", "Sam Newman", "O'Reilly Media", "2nd Edition", "2021"],
    ["Domain-Driven Design", "Eric Evans", "Addison-Wesley", "1st Edition", "2003"],
    ["Clean Architecture", "Robert C. Martin", "Prentice Hall", "1st Edition", "2017"],
    ["The Mythical Man-Month", "Frederick P. Brooks Jr.", "Addison-Wesley", "2nd Edition", "1995"],
    ["Head First Agile", "Andrew Stellman, Jennifer Greene", "O'Reilly Media", "1st Edition", "2017"],
    ["Fundamentals of Software Architecture", "Mark Richards, Neal Ford", "O'Reilly Media", "1st Edition", "2020"],
    ["Agile Software Development: Principles, Patterns, and Practices", "Robert C. Martin", "Pearson", "1st Edition", "2002"],
    ["Software Engineering at Google", "Titus Winters, Tom Manshreck, Hyrum Wright", "O'Reilly Media", "1st Edition", "2020"],
    ["System Design Interview", "Alex Xu", "ByteByteGo", "2nd Edition", "2020"],
    ["Test-Driven Development: By Example", "Kent Beck", "Addison-Wesley", "1st Edition", "2002"],
    ["Extreme Programming Explained", "Kent Beck, Cynthia Andres", "Addison-Wesley", "2nd Edition", "2004"],
    ["Release It!: Design and Deploy Production-Ready Software", "Michael T. Nygard", "Pragmatic Bookshelf", "2nd Edition", "2018"],
    ["User Stories Applied", "Mike Cohn", "Addison-Wesley", "1st Edition", "2004"],
    ["Agile Estimating and Planning", "Mike Cohn", "Prentice Hall", "1st Edition", "2005"],
    ["Software Architecture in Practice", "Len Bass, Paul Clements, Rick Kazman", "Addison-Wesley", "4th Edition", "2021"],
    ["Clean Agile", "Robert C. Martin", "Prentice Hall", "1st Edition", "2019"],
    ["Team Topologies", "Matthew Skelton, Manuel Pais", "IT Revolution Press", "1st Edition", "2019"],
    ["Designing Data-Intensive Applications", "Martin Kleppmann", "O'Reilly Media", "1st Edition", "2017"],
    ["Patterns of Enterprise Application Architecture", "Martin Fowler", "Addison-Wesley", "1st Edition", "2002"],
    ["Software Requirement Engineering", "Karl Wiegers, Joy Beatty", "Microsoft Press", "3rd Edition", "2013"],
    ["Software Testing: A Craftsman's Approach", "Paul C. Jorgensen", "CRC Press", "5th Edition", "2021"],
    ["Object-Oriented Software Construction", "Bertrand Meyer", "Prentice Hall", "2nd Edition", "1997"],
    ["Accelerate: The Science of Lean Software and DevOps", "Nicole Forsgren, Jez Humble, Gene Kim", "IT Revolution Press", "1st Edition", "2018"],
    ["Software Architecture for Developers", "Simon Brown", "C4 Model", "2nd Edition", "2018"],
    ["Microservice Architecture", "Irakli Nadareishvili, Ronnie Mitra", "O'Reilly Media", "1st Edition", "2016"],
    ["Modern Software Engineering", "David Farley", "Addison-Wesley", "1st Edition", "2021"],
    ["Righting Software", "Nicholas Juarez", "Addison-Wesley", "1st Edition", "2019"],
    ["Clean Craftsmanship", "Robert C. Martin", "Prentice Hall", "1st Edition", "2021"],
    ["Software Engineering for Real-Time Systems", "Jim Cooling", "Addison-Wesley", "1st Edition", "2002"],
    ["Managing the Software Process", "Watts S. Humphrey", "Addison-Wesley", "1st Edition", "1989"],
    ["Software Configuration Management Patterns", "Stephen P. Berczuk, Brad Appleton", "Addison-Wesley", "1st Edition", "2003"],
    ["The DevOps Handbook", "Gene Kim, Jez Humble, Patrick Debois", "IT Revolution Press", "2nd Edition", "2021"],
    ["Site Reliability Engineering", "Betsy Beyer, Chris Jones, Jennifer Petoff", "O'Reilly Media", "1st Edition", "2016"]
  ],
  "AI": [
    ["Artificial Intelligence: A Modern Approach", "Stuart Russell, Peter Norvig", "Pearson", "4th Edition", "2020"],
    ["Deep Learning", "Ian Goodfellow, Yoshua Bengio, Aaron Courville", "MIT Press", "1st Edition", "2016"],
    ["Pattern Recognition and Machine Learning", "Christopher M. Bishop", "Springer", "1st Edition", "2006"],
    ["Machine Learning", "Tom M. Mitchell", "McGraw-Hill", "1st Edition", "1997"],
    ["Reinforcement Learning: An Introduction", "Richard S. Sutton, Andrew G. Barto", "MIT Press", "2nd Edition", "2018"],
    ["Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", "Aurélien Géron", "O'Reilly Media", "3rd Edition", "2022"],
    ["Speech and Language Processing", "Dan Jurafsky, James H. Martin", "Pearson", "3rd Edition", "2021"],
    ["Computer Vision: Algorithms and Applications", "Richard Szeliski", "Springer", "2nd Edition", "2022"],
    ["Mathematics for Machine Learning", "Marc Peter Deisenroth, A. Aldo Faisal", "Cambridge University Press", "1st Edition", "2020"],
    ["Artificial Intelligence: Foundations of Computational Agents", "David L. Poole, Alan K. Mackworth", "Cambridge University Press", "2nd Edition", "2017"],
    ["Neural Networks and Deep Learning", "Michael Nielsen", "Determination Press", "1st Edition", "2015"],
    ["Probabilistic Graphical Models", "Daphne Koller, Nir Friedman", "MIT Press", "1st Edition", "2009"],
    ["Machine Learning: A Probabilistic Perspective", "Kevin P. Murphy", "MIT Press", "1st Edition", "2012"],
    ["Deep Learning with Python", "François Chollet", "Manning Publications", "2nd Edition", "2021"],
    ["Generative Deep Learning", "David Foster", "O'Reilly Media", "2nd Edition", "2023"],
    ["Natural Language Processing with Transformers", "Lewis Tunstall, Leandro von Werra", "O'Reilly Media", "1st Edition", "2022"],
    ["Practical Natural Language Processing", "Sowmya Vajjala, Bodhisattwa Majumder", "O'Reilly Media", "1st Edition", "2020"],
    ["Computer Vision: Models, Learning, and Inference", "Simon J. D. Prince", "Cambridge University Press", "1st Edition", "2012"],
    ["Machine Learning Yearning", "Andrew Ng", "DeepLearning.AI", "1st Edition", "2018"],
    ["Bayesian Reasoning and Machine Learning", "David Barber", "Cambridge University Press", "1st Edition", "2012"],
    ["Foundations of Computer Vision", "Antonio Torralba, Phillip Isola", "MIT Press", "1st Edition", "2024"],
    ["Artificial Intelligence in Practice", "Bernard Marr", "Wiley", "1st Edition", "2019"],
    ["Life 3.0: Being Human in the Age of Artificial Intelligence", "Max Tegmark", "Vintage", "1st Edition", "2017"],
    ["Superintelligence: Paths, Dangers, Strategies", "Nick Bostrom", "Oxford University Press", "1st Edition", "2014"],
    ["Deep Reinforcement Learning Hands-On", "Maxim Lapan", "Packt Publishing", "2nd Edition", "2020"],
    ["Interpretable Machine Learning", "Christoph Molnar", "Lulu Press", "2nd Edition", "2022"],
    ["Machine Learning Design Patterns", "Valliappa Lakshmanan, Sara Robinson", "O'Reilly Media", "1st Edition", "2020"],
    ["AI Superpowers: China, Silicon Valley, and the New World Order", "Kai-Fu Lee", "Houghton Mifflin Harcourt", "1st Edition", "2018"],
    ["The Master Algorithm", "Pedro Domingos", "Basic Books", "1st Edition", "2015"],
    ["Machine Learning Engineering", "Andriy Burkov", "True Positive Inc", "1st Edition", "2020"],
    ["The Hundred-Page Machine Learning Book", "Andriy Burkov", "True Positive Inc", "1st Edition", "2019"],
    ["Deep Learning for Coders with fastai and PyTorch", "Jeremy Howard, Sylvain Gugger", "O'Reilly Media", "1st Edition", "2020"],
    ["Applied Predictive Modeling", "Max Kuhn, Kjell Johnson", "Springer", "1st Edition", "2013"],
    ["Evolutionary Computation: A Unified Approach", "Kenneth A. De Jong", "MIT Press", "1st Edition", "2006"],
    ["Knowledge Representation and Reasoning", "Ronald Brachman, Hector Levesque", "Morgan Kaufmann", "1st Edition", "2004"],
    ["Swarm Intelligence", "James Kennedy, Russell C. Eberhart", "Morgan Kaufmann", "1st Edition", "2001"],
    ["Fuzzy Logic with Engineering Applications", "Timothy J. Ross", "Wiley", "4th Edition", "2016"],
    ["Artificial Intelligence: A Guide for Thinking Humans", "Melanie Mitchell", "Farrar, Straus and Giroux", "1st Edition", "2019"],
    ["Machine Learning for Algorithmic Trading", "Stefan Jansen", "Packt Publishing", "2nd Edition", "2020"],
    ["Causal Inference in Statistics", "Judea Pearl, Madelyn Glymour", "Wiley", "1st Edition", "2016"],
    ["The Book of Why: The New Science of Cause and Effect", "Judea Pearl, Dana Mackenzie", "Basic Books", "1st Edition", "2018"],
    ["Deep Learning for Vision Systems", "Mohamed Elgendy", "Manning Publications", "1st Edition", "2020"]
  ],
  "IT": [
    ["Management Information Systems", "Kenneth C. Laudon, Jane P. Laudon", "Pearson", "16th Edition", "2019"],
    ["Cloud Computing: Concepts, Technology & Architecture", "Thomas Erl, Zaigham Mahmood", "Prentice Hall", "1st Edition", "2013"],
    ["Network Essentials", "Jeffrey S. Beasley, Piyasat Nilkaew", "Pearson", "5th Edition", "2018"],
    ["Cisco CCNA Routing and Switching Complete Study Guide", "Todd Lammle", "Sybex", "2nd Edition", "2016"],
    ["Cybersecurity Essentials", "Charles J. Brooks, Christopher Grow", "Sybex", "1st Edition", "2018"],
    ["IT Governance: How Top Performers Manage IT Decision Rights", "Peter Weill, Jeanne W. Ross", "Harvard Business Review Press", "1st Edition", "2004"],
    ["The Practice of System and Network Administration", "Thomas A. Limoncelli", "Addison-Wesley", "3rd Edition", "2016"],
    ["CompTIA Security+ Guide to Network Security Fundamentals", "Mark Ciampa", "Cengage Learning", "7th Edition", "2021"],
    ["Database Administration: The Complete Guide to Practices", "Craig S. Mullins", "Addison-Wesley", "2nd Edition", "2012"],
    ["Information Technology Project Management", "Kathy Schwalbe", "Cengage Learning", "9th Edition", "2018"],
    ["Data Center Fundamentals", "Maurizio Portolani, Mauricio Arregoces", "Cisco Press", "1st Edition", "2003"],
    ["System Analysis and Design", "Alan Dennis, Barbara Haley Wixom", "Wiley", "7th Edition", "2018"],
    ["Business Data Communications and Networking", "Jerry FitzGerald, Alan Dennis", "Wiley", "14th Edition", "2020"],
    ["Network Security Essentials", "William Stallings", "Pearson", "6th Edition", "2016"],
    ["IT Infrastructure Architecture", "Sjaak Laan", "Lulu Press", "3rd Edition", "2017"],
    ["Web Technologies: A Computer Science Perspective", "Jeffrey C. Jackson", "Pearson", "1st Edition", "2006"],
    ["Cloud Systems Administration", "Thomas A. Limoncelli", "Addison-Wesley", "1st Edition", "2014"],
    ["Enterprise Systems for Management", "Luvai Motiwalla, Jeffrey Thompson", "Pearson", "2nd Edition", "2011"],
    ["Information Security Principles and Practice", "Mark Stamp", "Wiley", "3rd Edition", "2021"],
    ["CISSP Official Study Guide", "Mike Chapple, James Michael Stewart", "Sybex", "9th Edition", "2021"],
    ["Principles of Database Management", "Wilfried Lemahieu, Seppe vanden Broucke", "Cambridge University Press", "1st Edition", "2018"],
    ["IT Strategy: Issues and Practices", "James D. McKeen, Heather A. Smith", "Pearson", "4th Edition", "2018"],
    ["Fundamentals of Wireless Communication", "David Tse, Pramod Viswanath", "Cambridge University Press", "1st Edition", "2005"],
    ["Ethical Hacking and Penetration Testing Guide", "Rafay Baloch", "CRC Press", "1st Edition", "2014"],
    ["Computer Forensics and Digital Investigation", "John Vacca", "McGraw-Hill", "2nd Edition", "2010"],
    ["Enterprise Architecture at Work", "Marc Lankhorst", "Springer", "4th Edition", "2017"],
    ["Big Data: Principles and Best Practices", "Nathan Marz, James Warren", "Manning Publications", "1st Edition", "2015"],
    ["Information Technology Law", "Ian Lloyd", "Oxford University Press", "9th Edition", "2020"],
    ["Service Management: Operations, Strategy, IT", "Sanjeev Bordoloi, James Fitzsimmons", "McGraw-Hill", "10th Edition", "2022"],
    ["IT Service Management: ITIL Foundation", "Jan van Bon", "Van Haren Publishing", "4th Edition", "2019"],
    ["Wireless Networking Principles and Applications", "Lijun Dong", "Springer", "1st Edition", "2021"],
    ["Disaster Recovery and Business Continuity", "Theodore Diaconoff", "Rothstein Publishing", "2nd Edition", "2012"],
    ["Storage Area Network Essentials", "Richard Barker", "Wiley", "1st Edition", "2002"],
    ["Linux System Administration Handbook", "Evi Nemeth, Gareth White", "Addison-Wesley", "5th Edition", "2017"],
    ["Windows Server 2022 Administration Fundamentals", "Crystal Panek", "Packt Publishing", "2nd Edition", "2022"],
    ["DevSecOps: Securing Software Pipelines", "Julien Vehent", "Manning Publications", "1st Edition", "2020"],
    ["Data Analytics for IT Leaders", "Thomas Davenport", "Harvard Business Review Press", "1st Edition", "2018"],
    ["Virtualization Essentials", "Matthew Portnoy", "Sybex", "3rd Edition", "2020"],
    ["Internet of Things: A Hands-On Approach", "Arshdeep Bahga, Vijay Madisetti", "VP-Universities Press", "1st Edition", "2014"],
    ["Information Technology Auditing", "James A. Hall", "Cengage Learning", "4th Edition", "2015"],
    ["Infrastructure as Code", "Kief Morris", "O'Reilly Media", "2nd Edition", "2020"],
    ["High Performance Data Network Design", "David Newman", "Wiley", "1st Edition", "2001"]
  ],
  "Accounting and Finance": [
    ["Financial Accounting", "Robert Libby, Patricia Libby, Frank Hodge", "McGraw-Hill", "10th Edition", "2019"],
    ["Managerial Accounting", "Ray H. Garrison, Eric W. Noreen, Peter C. Brewer", "McGraw-Hill", "17th Edition", "2020"],
    ["Principles of Corporate Finance", "Richard A. Brealey, Stewart C. Myers, Franklin Allen", "McGraw-Hill", "13th Edition", "2019"],
    ["Corporate Finance", "Stephen A. Ross, Randolph W. Westerfield, Jeffrey Jaffe", "McGraw-Hill", "12th Edition", "2018"],
    ["Intermediate Accounting", "Donald E. Kieso, Jerry J. Weygandt, Terry D. Warfield", "Wiley", "18th Edition", "2022"],
    ["Fundamentals of Financial Management", "Eugene F. Brigham, Joel F. Houston", "Cengage Learning", "15th Edition", "2018"],
    ["Financial Statement Analysis", "K. R. Subramanyam", "McGraw-Hill", "11th Edition", "2014"],
    ["Valuation: Measuring and Managing the Value of Companies", "McKinsey & Company", "Wiley", "7th Edition", "2020"],
    ["Cost Accounting: A Managerial Emphasis", "Charles T. Horngren, Srikant M. Datar", "Pearson", "16th Edition", "2017"],
    ["Financial Markets and Institutions", "Frederic S. Mishkin, Stanley Eakins", "Pearson", "9th Edition", "2017"],
    ["Investments", "Zvi Bodie, Alex Kane, Alan J. Marcus", "McGraw-Hill", "12th Edition", "2020"],
    ["Auditing and Assurance Services", "Alvin A. Arens, Randal J. Elder, Mark S. Beasley", "Pearson", "17th Edition", "2019"],
    ["Personal Finance", "E. Thomas Garman, Raymond E. Forgue", "Cengage Learning", "13th Edition", "2017"],
    ["Accounting Information Systems", "Marshall B. Romney, Paul J. Steinbart", "Pearson", "15th Edition", "2020"],
    ["International Financial Management", "Jeff Madura", "Cengage Learning", "14th Edition", "2020"],
    ["Options, Futures, and Other Derivatives", "John C. Hull", "Pearson", "11th Edition", "2021"],
    ["The Intelligent Investor", "Benjamin Graham", "Harper Business", "Revised Edition", "2006"],
    ["Security Analysis", "Benjamin Graham, David Dodd", "McGraw-Hill", "6th Edition", "2008"],
    ["Principles of Accounting", "Belverd E. Needles, Marian Powers", "Cengage Learning", "12th Edition", "2013"],
    ["Financial Accounting: IFRS Edition", "Jerry J. Weygandt, Paul D. Kimmel", "Wiley", "4th Edition", "2018"],
    ["Advanced Financial Accounting", "David M. Cottrell, Theodore Christensen", "McGraw-Hill", "12th Edition", "2018"],
    ["Financial Risk Management", "Steve L. Allen", "Wiley", "2nd Edition", "2012"],
    ["Behavioral Finance: Psychology, Decision-Making, and Markets", "Lucy Ackert, Richard Deaves", "Cengage Learning", "1st Edition", "2009"],
    ["Taxation of Individuals and Business Entities", "Brian Spilker", "McGraw-Hill", "13th Edition", "2021"],
    ["Forensic Accounting and Fraud Examination", "Mary-Jo Kranacher, Richard Riley", "Wiley", "2nd Edition", "2019"],
    ["Fixed Income Securities", "Frank J. Fabozzi", "Wiley", "2nd Edition", "2001"],
    ["Mergers, Acquisitions, and Corporate Restructurings", "Patrick A. Gaughan", "Wiley", "7th Edition", "2017"],
    ["Portfolio Management", "Frank J. Fabozzi", "Wiley", "1st Edition", "2021"],
    ["Microeconomics for Finance", "Hal R. Varian", "W. W. Norton & Company", "9th Edition", "2014"],
    ["Macroeconomics and Financial Markets", "N. Gregory Mankiw", "Worth Publishers", "10th Edition", "2019"],
    ["Quantitative Financial Economics", "Keith Cuthbertson, Dirk Nitzsche", "Wiley", "2nd Edition", "2004"],
    ["Bank Management and Financial Services", "Peter S. Rose, Sylvia C. Hudgins", "McGraw-Hill", "9th Edition", "2012"],
    ["Management Accounting for Decision Making", "Anthony A. Atkinson", "Pearson", "6th Edition", "2011"],
    ["Financial Derivatives: Theory and Practice", "J. C. Francis", "McGraw-Hill", "1st Edition", "2000"],
    ["Applied Corporate Finance", "Aswath Damodaran", "Wiley", "4th Edition", "2014"],
    ["Damodaran on Valuation", "Aswath Damodaran", "Wiley", "2nd Edition", "2006"],
    ["Public Finance and Public Policy", "Jonathan Gruber", "Worth Publishers", "6th Edition", "2019"],
    ["International Accounting", "Timothy Doupnik, Hector Perera", "McGraw-Hill", "5th Edition", "2019"],
    ["Real Estate Finance and Investments", "William Brueggeman, Jeffrey Fisher", "McGraw-Hill", "16th Edition", "2018"],
    ["Commercial Bank Management", "E. W. Reed", "Prentice Hall", "5th Edition", "1996"],
    ["Financial Analytics with R", "Mark J. Bennett, Dirk L. Hugen", "Cambridge University Press", "1st Edition", "2016"],
    ["Accounting for Managers", "Paul M. Collier", "Wiley", "5th Edition", "2015"]
  ],
  "Education": [
    ["Educational Psychology", "Anita Woolfolk", "Pearson", "14th Edition", "2018"],
    ["Foundations of American Education", "L. Dean Webb, Arlene Metha", "Pearson", "8th Edition", "2016"],
    ["Teaching to Transgress: Education as the Practice of Freedom", "bell hooks", "Routledge", "1st Edition", "1994"],
    ["Democracy and Education", "John Dewey", "Free Press", "1st Edition", "1916"],
    ["Curriculum Development: Theory and Practice", "Hilda Taba", "Harcourt Brace", "1st Edition", "1962"],
    ["Classroom Management for Teachers", "Carolyn M. Evertson, Edmund T. Emmer", "Pearson", "10th Edition", "2016"],
    ["Instructional Technology and Media for Learning", "Sharon E. Smaldino", "Pearson", "12th Edition", "2018"],
    ["Educational Research", "John W. Creswell", "Pearson", "6th Edition", "2018"],
    ["Pedagogy of the Oppressed", "Paulo Freire", "Bloomsbury Academic", "50th Anniversary Edition", "2018"],
    ["How People Learn", "National Research Council", "National Academies Press", "Expanded Edition", "2000"],
    ["Assessment in Special and Inclusive Education", "John Salvia, James E. Ysseldyke", "Cengage Learning", "13th Edition", "2016"],
    ["Developing the Curriculum", "Peter F. Oliva, William R. Gordon", "Pearson", "8th Edition", "2012"],
    ["Teacher Evaluation That Makes a Difference", "Robert J. Marzano", "ASCD", "1st Edition", "2013"],
    ["Educational Leadership: Concepts and Practices", "Fred C. Lunenburg", "Sage Publications", "7th Edition", "2020"],
    ["Qualitative Research in Education", "Robert C. Bogdan, Sari Knopp Biklen", "Pearson", "5th Edition", "2006"],
    ["Differentiated Instruction in the Classroom", "Carol Ann Tomlinson", "ASCD", "2nd Edition", "2017"],
    ["Philosophy of Education", "Nel Noddings", "Westview Press", "4th Edition", "2015"],
    ["The Courage to Teach", "Parker J. Palmer", "Jossey-Bass", "20th Anniversary Edition", "2017"],
    ["Educational Assessment of Students", "Anthony J. Nitko, Susan M. Brookhart", "Pearson", "7th Edition", "2014"],
    ["Special Education in Contemporary Society", "Richard M. Gargiulo", "Sage Publications", "7th Edition", "2020"],
    ["Multicultural Education: Issues and Perspectives", "James A. Banks", "Wiley", "10th Edition", "2019"],
    ["Early Childhood Education Today", "George S. Morrison", "Pearson", "14th Edition", "2017"],
    ["Principles of Classroom Management", "James Levin, John F. Nolan", "Pearson", "8th Edition", "2013"],
    ["Measurement and Evaluation in Teaching", "Norman E. Gronlund", "Macmillan", "8th Edition", "1998"],
    ["School Law and the Public Schools", "Nathan L. Essex", "Pearson", "6th Edition", "2015"],
    ["Comparative Education: Research Methods", "Mark Bray, Bob Adamson", "Springer", "2nd Edition", "2014"],
    ["History of Western Education", "James Bowen", "Routledge", "3rd Edition", "2003"],
    ["Educational Policy and Leadership", "Thomas J. Sergiovanni", "Pearson", "6th Edition", "2008"],
    ["Designing Effective Instruction", "Gary R. Morrison, Steven M. Ross", "Wiley", "8th Edition", "2019"],
    ["Learning Theories: An Educational Perspective", "Dale H. Schunk", "Pearson", "8th Edition", "2019"],
    ["Mindset: The New Psychology of Success", "Carol S. Dweck", "Ballantine Books", "Updated Edition", "2006"],
    ["Visible Learning for Teachers", "John Hattie", "Routledge", "1st Edition", "2012"],
    ["Responsive Teaching", "Harry Fletcher-Wood", "Routledge", "1st Edition", "2018"],
    ["Educational Technology in the Classroom", "Timothy J. Newby", "Pearson", "8th Edition", "2018"],
    ["Constructivism in Education", "Leslie P. Steffe, Jerry Gale", "Routledge", "1st Edition", "1995"],
    ["Sociology of Education", "Jeanne H. Ballantine", "Routledge", "8th Edition", "2017"],
    ["Language and Learning in the Early Years", "Eve Bearne", "Routledge", "2nd Edition", "2002"],
    ["Action Research in Education", "Ernie Stringer", "Pearson", "4th Edition", "2013"],
    ["Teacher Training and Professional Development", "Linda Darling-Hammond", "Jossey-Bass", "1st Edition", "2005"],
    ["Critical Pedagogy: Notes from the Real World", "Joan Wink", "Pearson", "4th Edition", "2010"],
    ["Experiential Learning", "David A. Kolb", "Pearson", "2nd Edition", "2014"],
    ["Effective Teaching Methods", "Gary D. Borich", "Pearson", "9th Edition", "2016"]
  ],
  "BBA Education": [
    ["Business Communication Today", "Courtland L. Bovee, John V. Thill", "Pearson", "15th Edition", "2020"],
    ["Principles of Marketing", "Philip Kotler, Gary Armstrong", "Pearson", "18th Edition", "2020"],
    ["Organizational Behavior", "Stephen P. Robbins, Timothy A. Judge", "Pearson", "18th Edition", "2018"],
    ["Human Resource Management", "Gary Dessler", "Pearson", "16th Edition", "2019"],
    ["Strategic Management: Concepts and Cases", "Fred R. David, Forest R. David", "Pearson", "17th Edition", "2019"],
    ["Operations Management", "Jay Heizer, Barry Render", "Pearson", "13th Edition", "2019"],
    ["Business Statistics: A First Course", "David M. Levine, Kathryn A. Szabat", "Pearson", "8th Edition", "2019"],
    ["Business Ethics: Concepts and Cases", "Manuel G. Velasquez", "Pearson", "8th Edition", "2017"],
    ["Entrepreneurship: Launching New Ventures", "Bruce R. Barringer", "Pearson", "6th Edition", "2018"],
    ["International Business", "Charles W. L. Hill", "McGraw-Hill", "13th Edition", "2020"],
    ["Principles of Management", "Ricky W. Griffin", "Cengage Learning", "13th Edition", "2021"],
    ["Business Research Methods", "Donald R. Cooper, Pamela S. Schindler", "McGraw-Hill", "12th Edition", "2013"],
    ["Consumer Behavior", "Leon G. Schiffman, Joe Wisenblit", "Pearson", "12th Edition", "2018"],
    ["Supply Chain Management: Strategy, Planning", "Sunil Chopra", "Pearson", "7th Edition", "2018"],
    ["Business Law: Text and Cases", "Kenneth W. Clarkson, Roger LeRoy Miller", "Cengage Learning", "15th Edition", "2020"],
    ["Managerial Economics", "Luke M. Froeb, Brian T. McCann", "Cengage Learning", "5th Edition", "2017"],
    ["Advertising and Promotion", "George E. Belch, Michael A. Belch", "McGraw-Hill", "12th Edition", "2020"],
    ["Leadership in Organizations", "Gary Yukl", "Pearson", "9th Edition", "2019"],
    ["E-Commerce: Business, Technology, Society", "Kenneth C. Laudon", "Pearson", "16th Edition", "2020"],
    ["Project Management: The Managerial Process", "Erik W. Larson, Clifford F. Gray", "McGraw-Hill", "8th Edition", "2020"],
    ["Quantitative Techniques in Management", "N. D. Vohra", "McGraw-Hill", "5th Edition", "2017"],
    ["Sales Management: Analysis and Decision Making", "David L. Kurtz", "Routledge", "10th Edition", "2020"],
    ["Total Quality Management", "Joel E. Ross", "CRC Press", "3rd Edition", "2017"],
    ["Strategic Brand Management", "Kevin Lane Keller", "Pearson", "5th Edition", "2019"],
    ["Global Marketing", "Warren J. Keegan, Mark C. Green", "Pearson", "10th Edition", "2019"],
    ["Services Marketing: People, Technology", "Jochen Wirtz, Christopher Lovelock", "World Scientific", "9th Edition", "2021"],
    ["Business Analytics: Data Analysis", "S. Christian Albright", "Cengage Learning", "7th Edition", "2019"],
    ["Corporate Strategy", "Robert M. Grant", "Wiley", "10th Edition", "2018"],
    ["Innovation and Entrepreneurship", "Peter F. Drucker", "Harper Business", "Reissue Edition", "2006"],
    ["Negotiations and Resolving Conflicts", "Roy J. Lewicki", "McGraw-Hill", "8th Edition", "2019"],
    ["Managing Information Technology in Business", "James O'Brien", "McGraw-Hill", "10th Edition", "2011"],
    ["Cross-Cultural Management", "David C. Thomas", "Sage Publications", "4th Edition", "2017"],
    ["Retail Management: A Strategic Approach", "Barry Berman", "Pearson", "13th Edition", "2017"],
    ["Small Business Management", "Justin G. Longenecker", "Cengage Learning", "19th Edition", "2019"],
    ["Management Science: Modeling with Spreadsheets", "Stephen G. Powell", "Wiley", "5th Edition", "2016"],
    ["Digital Marketing Strategy", "Simon Kingsnorth", "Kogan Page", "3rd Edition", "2022"],
    ["Organizational Theory, Design, and Change", "Gareth R. Jones", "Pearson", "7th Edition", "2012"],
    ["Business Policy and Environment", "Francis Cherunilam", "Himalaya Publishing", "10th Edition", "2018"],
    ["Performance Management", "Herman Aguinis", "Chicago Business Press", "4th Edition", "2019"],
    ["Change Management", "Robert A. Paton, James McCalman", "Sage Publications", "5th Edition", "2016"],
    ["Corporate Social Responsibility", "David Crowther", "Bookboon", "1st Edition", "2008"],
    ["Strategic Human Resource Management", "Jeffrey A. Mello", "Cengage Learning", "5th Edition", "2019"]
  ],
  "English Literature": [
    ["The Norton Anthology of English Literature", "Stephen Greenblatt", "W. W. Norton & Company", "10th Edition", "2018"],
    ["A Critical History of English Literature", "David Daiches", "Allied Publishers", "2nd Edition", "1994"],
    ["Literary Theory: An Introduction", "Terry Eagleton", "Wiley-Blackwell", "3rd Edition", "2008"],
    ["Hamlet", "William Shakespeare", "Arden Shakespeare", "3rd Edition", "2006"],
    ["Macbeth", "William Shakespeare", "Folger Shakespeare Library", "Reissue Edition", "2004"],
    ["Pride and Prejudice", "Jane Austen", "Penguin Classics", "Deluxe Edition", "2002"],
    ["Jane Eyre", "Charlotte Brontë", "Penguin Classics", "Reissue Edition", "2006"],
    ["Wuthering Heights", "Emily Brontë", "Oxford World's Classics", "Reissue Edition", "2009"],
    ["Great Expectations", "Charles Dickens", "Penguin Classics", "Reissue Edition", "2002"],
    ["The Great Gatsby", "F. Scott Fitzgerald", "Scribner", "Definitive Edition", "2004"],
    ["To Kill a Mockingbird", "Harper Lee", "Harper Perennial", "50th Anniversary Edition", "2010"],
    ["1984", "George Orwell", "Signet Classics", "Reissue Edition", "1950"],
    ["Animal Farm", "George Orwell", "Signet Classics", "Reissue Edition", "1996"],
    ["Lord of the Flies", "William Golding", "Penguin Books", "Reissue Edition", "2003"],
    ["Frankenstein", "Mary Shelley", "Penguin Classics", "200th Anniversary Edition", "2018"],
    ["Paradise Lost", "John Milton", "Penguin Classics", "Reissue Edition", "2003"],
    ["The Canterbury Tales", "Geoffrey Chaucer", "Penguin Classics", "Reissue Edition", "2003"],
    ["Ulysses", "James Joyce", "Vintage", "Modern Library Edition", "1990"],
    ["Heart of Darkness", "Joseph Conrad", "Penguin Classics", "Reissue Edition", "2007"],
    ["The Waste Land and Other Poems", "T.S. Eliot", "Faber & Faber", "Centenary Edition", "2022"],
    ["Waiting for Godot", "Samuel Beckett", "Grove Press", "Reissue Edition", "2011"],
    ["Things Fall Apart", "Chinua Achebe", "Anchor Books", "50th Anniversary Edition", "2008"],
    ["Beloved", "Toni Morrison", "Vintage", "Reissue Edition", "2004"],
    ["One Hundred Years of Solitude", "Gabriel García Márquez", "Harper Perennial", "Deluxe Edition", "2006"],
    ["Crime and Punishment", "Fyodor Dostoevsky", "Penguin Classics", "Translated Edition", "2002"],
    ["Modern Critical Theory and Practice", "Nigel Fabb", "Routledge", "2nd Edition", "2002"],
    ["An Introduction to Literary Studies", "Mario Klarer", "Routledge", "3rd Edition", "2013"],
    ["Shakespeare: The Invention of the Human", "Harold Bloom", "Riverhead Books", "1st Edition", "1998"],
    ["The Anatomy of Criticism", "Northrop Frye", "Princeton University Press", "Reissue Edition", "2000"],
    ["Orientalism", "Edward W. Said", "Vintage", "25th Anniversary Edition", "1979"],
    ["Culture and Imperialism", "Edward W. Said", "Vintage", "1st Edition", "1993"],
    ["Practical Criticism", "I.A. Richards", "Routledge", "Reissue Edition", "2008"],
    ["The Oxford Companion to English Literature", "Dinah Birch", "Oxford University Press", "7th Edition", "2009"],
    ["History of English Poetry", "W.J. Courthope", "Macmillan", "Reissue Edition", "1903"],
    ["The Sound and the Fury", "William Faulkner", "Vintage", "Corrected Edition", "1990"],
    ["Mrs. Dalloway", "Virginia Woolf", "Harvest Book", "Annotated Edition", "2005"],
    ["To the Lighthouse", "Virginia Woolf", "Harvest Book", "Reissue Edition", "1989"],
    ["The Odyssey", "Homer (Translated by Robert Fagles)", "Penguin Classics", "Deluxe Edition", "1996"],
    ["The Iliad", "Homer (Translated by Robert Fagles)", "Penguin Classics", "Deluxe Edition", "1998"],
    ["Pygmalion", "George Bernard Shaw", "Penguin Classics", "Reissue Edition", "2003"],
    ["A Passage to India", "E.M. Forster", "Harcourt", "Harvest Edition", "1984"],
    ["The Picture of Dorian Gray", "Oscar Wilde", "Penguin Classics", "Reissue Edition", "2003"]
  ]
};

let books = [];
let idCounter = 1000;

for (const [dept, list] of Object.entries(rawData)) {
  let idx = 1;
  for (const item of list) {
    const [title, author, publisher, edition, year] = item;
    const totalCopies = 5;
    const availableCopies = 5;
    
    books.push({
      id: `B${idCounter++}`,
      accessionNumber: `ACC-2026-${idCounter}`,
      isbn13: `978-${Math.floor(1000000000 + Math.random() * 9000000000)}`,
      name: title,
      author: author,
      publisher: publisher,
      edition: edition,
      publicationYear: year || "2021",
      language: "English",
      department: dept,
      semester: ((idx % 8) + 1).toString(),
      subject: `Core ${dept}`,
      shelfNumber: ((idx % 12) + 1).toString(),
      rackNumber: String.fromCharCode(65 + (idx % 6)), // A, B, C, D, E, F
      rowNumber: ((idx % 4) + 1).toString(),
      floor: idx % 2 === 0 ? "Main Floor" : "1st Floor",
      totalCopies: totalCopies,
      availableCopies: availableCopies,
      issuedCopies: 0,
      reservedCopies: 0,
      lostCopies: 0,
      damagedCopies: 0,
      status: "Available"
    });
    idx++;
  }
}

console.log(`Generated ${books.length} real world books.`);

const content = `import { Book } from '@/src/types/index';

export const INITIAL_BOOKS: Book[] = ${JSON.stringify(books, null, 2)};
`;

fs.writeFileSync('src/data/booksData.ts', content);
fs.writeFileSync('src/data/booksData.json', JSON.stringify(books, null, 2));

