import { Book, Student } from './types';

export const INITIAL_BOOKS: Book[] = [
  { id: 'B001', name: 'Digital Logic Design (DLD)', author: 'M. Morris Mano', department: 'CS', status: 'Available' },
  { id: 'B002', name: 'Object Oriented Programming (OOP)', author: 'Robert Lafore', department: 'CS', status: 'Available' },
  { id: 'B003', name: 'C++ Programming', author: 'Bjarne Stroustrup', department: 'CS', status: 'Available' },
  { id: 'B004', name: 'Data Structures', author: 'Mark Allen Weiss', department: 'CS', status: 'Issued' },
  { id: 'B005', name: 'Database Systems', author: 'Elmasri & Navathe', department: 'CS', status: 'Available' },
  { id: 'B006', name: 'Calculus Early Transcendentals', author: 'James Stewart', department: 'Mathematics', status: 'Available' },
  { id: 'B007', name: 'Introduction to Algorithms', author: 'Thomas H. Cormen', department: 'CS', status: 'Available' },
  { id: 'B008', name: 'Clean Code', author: 'Robert C. Martin', department: 'CS', status: 'Available' },
  { id: 'B009', name: 'Design Patterns', author: 'Erich Gamma', department: 'Software Eng', status: 'Issued' },
  { id: 'B010', name: 'Computer Networking', author: 'James Kurose', department: 'IT', status: 'Available' },
  { id: 'B011', name: 'Artificial Intelligence', author: 'Peter Norvig', department: 'CS', status: 'Available' },
  { id: 'B012', name: 'Operating System Concepts', author: 'Abraham Silberschatz', department: 'CS', status: 'Available' },
  { id: 'B013', name: 'The Pragmatic Programmer', author: 'Andrew Hunt', department: 'Software Eng', status: 'Available' },
  { id: 'B014', name: 'Code Complete', author: 'Steve McConnell', department: 'Software Eng', status: 'Issued' },
  { id: 'B015', name: 'Structure and Interpretation of Computer Programs', author: 'Harold Abelson', department: 'CS', status: 'Available' },
  { id: 'B016', name: 'Theory of Computation', author: 'Michael Sipser', department: 'CS', status: 'Available' },
  { id: 'B017', name: 'Compilers: Principles', author: 'Alfred V. Aho', department: 'CS', status: 'Issued' },
  { id: 'B018', name: 'Modern Operating Systems', author: 'Andrew S. Tanenbaum', department: 'IT', status: 'Available' },
  { id: 'B019', name: 'Computer Architecture', author: 'John L. Hennessy', department: 'CS', status: 'Available' },
  { id: 'B020', name: 'Software Engineering', author: 'Ian Sommerville', department: 'Software Eng', status: 'Available' },
  { id: 'B021', name: 'Head First Design Patterns', author: 'Eric Freeman', department: 'Software Eng', status: 'Issued' },
  { id: 'B022', name: 'Refactoring', author: 'Martin Fowler', department: 'Software Eng', status: 'Available' },
  { id: 'B023', name: 'Domain-Driven Design', author: 'Eric Evans', department: 'Software Eng', status: 'Available' },
  { id: 'B024', name: 'Cracking the Coding Interview', author: 'Gayle Laakmann McDowell', department: 'General', status: 'Issued' },
  { id: 'B025', name: 'The Mythical Man-Month', author: 'Frederick P. Brooks Jr.', department: 'Software Eng', status: 'Available' },
  { id: 'B026', name: 'Don\'t Make Me Think', author: 'Steve Krug', department: 'IT', status: 'Available' },
  { id: 'B027', name: 'Sapiens', author: 'Yuval Noah Harari', department: 'General Knowledge', status: 'Available' },
  { id: 'B028', name: 'A Brief History of Time', author: 'Stephen Hawking', department: 'General Knowledge', status: 'Issued' },
  { id: 'B029', name: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', department: 'General Knowledge', status: 'Available' },
  { id: 'B030', name: 'The Selfish Gene', author: 'Richard Dawkins', department: 'General Knowledge', status: 'Available' },
  { id: 'B031', name: 'Guns, Germs, and Steel', author: 'Jared Diamond', department: 'General Knowledge', status: 'Issued' },
  { id: 'B032', name: 'Cosmos', author: 'Carl Sagan', department: 'General Knowledge', status: 'Available' },
  { id: 'B033', name: 'The Power of Habit', author: 'Charles Duhigg', department: 'General Knowledge', status: 'Available' },
  { id: 'B034', name: 'Outliers', author: 'Malcolm Gladwell', department: 'General Knowledge', status: 'Available' },
  { id: 'B035', name: 'Freakonomics', author: 'Steven D. Levitt', department: 'General Knowledge', status: 'Issued' },
  { id: 'B036', name: 'Blink', author: 'Malcolm Gladwell', department: 'General Knowledge', status: 'Available' },
  { id: 'B037', name: 'The Tipping Point', author: 'Malcolm Gladwell', department: 'General Knowledge', status: 'Available' },
  { id: 'B038', name: 'Quiet', author: 'Susan Cain', department: 'General Knowledge', status: 'Issued' },
  { id: 'B039', name: 'The Wright Brothers', author: 'David McCullough', department: 'General Knowledge', status: 'Available' },
  { id: 'B040', name: 'Steve Jobs', author: 'Walter Isaacson', department: 'General Knowledge', status: 'Available' },
  { id: 'B041', name: 'Einstein', author: 'Walter Isaacson', department: 'General Knowledge', status: 'Available' },
  { id: 'B042', name: 'Benjamin Franklin', author: 'Walter Isaacson', department: 'General Knowledge', status: 'Issued' },
  { id: 'B043', name: 'Henrietta Lacks', author: 'Rebecca Skloot', department: 'General Knowledge', status: 'Available' },
  { id: 'B044', name: 'Into the Wild', author: 'Jon Krakauer', department: 'General Knowledge', status: 'Available' },
  { id: 'B045', name: 'Unbroken', author: 'Laura Hillenbrand', department: 'General Knowledge', status: 'Issued' },
];

export const INITIAL_STUDENTS: Student[] = [
  { id: '2k26/CS/12', name: 'Ali Khan', department: 'CS', semester: 3, phone: '03001234567' },
  { id: '2k25/IT/10', name: 'Sara Ahmed', department: 'IT', semester: 5, phone: '03339876543' },
  { id: '2k24/SE/05', name: 'Muhammad Abdullah', department: 'Software Eng', semester: 7, phone: '03451122334' },
  { id: '2k26/CS/15', name: 'Fatima Noor', department: 'CS', semester: 2, phone: '03111223344' },
  { id: '2k25/CS/20', name: 'Bilal Hassan', department: 'CS', semester: 4, phone: '03221234567' },
  { id: '2k26/IT/01', name: 'Ayesha Malik', department: 'IT', semester: 1, phone: '03334567890' },
  { id: '2k24/CS/30', name: 'Omar Farooq', department: 'CS', semester: 6, phone: '03009876543' },
  { id: '2k25/SE/11', name: 'Zainab Tariq', department: 'Software Eng', semester: 3, phone: '03458765432' },
  { id: '2k23/CS/45', name: 'Usman Ali', department: 'CS', semester: 8, phone: '03123456789' },
  { id: '2k26/IT/08', name: 'Khadija Bibi', department: 'IT', semester: 2, phone: '03219876543' },
  { id: '2k25/CS/22', name: 'Hassan Raza', department: 'CS', semester: 5, phone: '03011223344' },
  { id: '2k26/SE/03', name: 'Maryam Zafar', department: 'Software Eng', semester: 1, phone: '03312345678' },
  { id: '2k24/CS/14', name: 'Kamran Saleem', department: 'CS', semester: 7, phone: '03419876543' },
  { id: '2k25/IT/19', name: 'Sana Javed', department: 'IT', semester: 4, phone: '03131234567' },
  { id: '2k26/CS/25', name: 'Hamza Shah', department: 'CS', semester: 2, phone: '03239876543' },
  { id: '2k24/SE/21', name: 'Nida Yasir', department: 'Software Eng', semester: 6, phone: '03021234567' },
  { id: '2k25/CS/33', name: 'Tariq Mehmood', department: 'CS', semester: 3, phone: '03329876543' },
  { id: '2k23/IT/40', name: 'Iqra Aziz', department: 'IT', semester: 8, phone: '03421234567' },
  { id: '2k26/CS/05', name: 'Fahad Mustafa', department: 'CS', semester: 1, phone: '03149876543' },
  { id: '2k25/SE/15', name: 'Mahira Khan', department: 'Software Eng', semester: 5, phone: '03241234567' },
  { id: '2k25/CS/18', name: 'Atif Aslam', department: 'CS', semester: 4, phone: '03031234567' },
  { id: '2k24/IT/25', name: 'Sajal Aly', department: 'IT', semester: 7, phone: '03339876543' },
  { id: '2k26/CS/31', name: 'Imran Abbas', department: 'CS', semester: 2, phone: '03431234567' },
  { id: '2k26/DS/12', name: 'Aliya Shah', department: 'DS', semester: 2, phone: '03341234567' },
  { id: '2k25/AI/07', name: 'Zaid Ali', department: 'AI', semester: 4, phone: '03441234567' },
  { id: '2k26/AI/14', name: 'Fatima Zahra', department: 'AI', semester: 1, phone: '03041234567' },
  { id: '2k25/DS/19', name: 'Ammar Yasir', department: 'DS', semester: 3, phone: '03151234567' },
  { id: '2k24/CS/55', name: 'Hania Amir', department: 'CS', semester: 6, phone: '03251234567' },
  { id: '2k26/SE/23', name: 'Sheheryar Munawar', department: 'Software Eng', semester: 2, phone: '03351234567' },
  { id: '2k25/IT/34', name: 'Mehwish Hayat', department: 'IT', semester: 5, phone: '03451234567' },
  { id: '2k26/DS/30', name: 'Fawad Khan', department: 'DS', semester: 1, phone: '03051234567' },
  { id: '2k24/AI/11', name: 'Maya Ali', department: 'AI', semester: 7, phone: '03161234567' },
];
